[project]
name = "web-scraper"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.13.2",
    "beautifulsoup4>=4.14.3",
    "loguru>=0.7.3",
    "lxml>=6.0.2",
    "streamlit>=1.52.2",
]
